### PR TITLE
additional adversary groups

### PR DESCRIPTION
**Pull request by cvandeplas**
Using as a source https://docs.google.com/spreadsheets/d/1H9_xaxQHpWaa4O_Son4Gx0YOIzlcBWMsdvePFX68EKU/edit

### CODE REVIEW

**Comment by adulau** [comment]
Usually the majority of the groups from Florian should be there too. But a regular review is required. If you know a way to automate the notification from Google, I would love it instead of doing it manually.

**Comment by adulau** [comment]
@cvandeplas If you know additional sources, let me know.

**Comment by cvandeplas** [comment]
I've set up email alerting, but I am not sure parsing that automatically is a good idea. 
Also, I've noticed multiple duplicates / inconsistencies in Florians document and this file (not present in this pull request) .
- PLA Navy : present multiple times in Florian's document
- Violin Panda : APT 8 and/or APT 20 ??
- Newscaster vs Charming Kitten:  split in Florian, merged in here

**Comment by adulau** [comment]
Thanks a lot for the contribution. If you have more, feel free ;-)

**Pull request merged**
