### PR TITLE
Merge microcin/sixlittlemonkeys to vicious panda

### PR DESCRIPTION
**Pull request by r0ny123**

### CODE REVIEW

**Comment by adulau** [comment]
Thank you. `Microcin` should be a synonym too then?

**Comment by r0ny123** [comment]
Actually forgot to mention, `microcin` is a malwre used by them.

**Comment by adulau** [comment]
Ok then it makes sense to add in https://github.com/MISP/misp-galaxy/blob/main/clusters/tool.json and make the relationship `used-by`.

**Comment by r0ny123** [comment]
Will do.

**Comment by r0ny123** [comment]
> Ok then it makes sense to add in https://github.com/MISP/misp-galaxy/blob/main/clusters/tool.json and make the relationship `used-by`.

@adulau, done in [f608312](https://github.com/MISP/misp-galaxy/pull/751/commits/f60831257723362f0057957c8aaff88108befc04).

**Comment by adulau** [comment]
@r0ny123 Thanks a lot!

**Pull request merged**
