### PR TITLE
[threat-actors] Remove SectorJ04 duplicate

### PR DESCRIPTION
**Pull request by Mathieu4141**

### CODE REVIEW

**Comment by adulau** [comment]
I would add SectorJ04 in the aliases.

**Comment by Mathieu4141** [comment]
> I would add SectorJ04 in the aliases.

Do you mean having both `SectorJ04 Group` and `SectorJ04`, or replace `SectorJ04 Group` with `SectorJ04`?

**Comment by adulau** [comment]
I mean having both.

**Comment by adulau** [comment]
Great! Thanks for the update.

**Pull request merged**
