### PR TITLE
Fix Cleaver aliases

### PR DESCRIPTION
**Pull request by Mathieu4141**
It seems to be a duplicate.

Most aliases of `Cutting Kitten` were aliases of `Cleaver` (except for `InfoSecTeam`), and of the 2 ref in `Cleaver`, 1 was in `Cutting Kitten` already

I'm not sure what's the policy in those cases, and if it's ok to merge?

### CODE REVIEW

**Comment by adulau** [comment]
Thanks a lot for the proposal. I see that the relationships are missing towards external clusters such ATT&CK. Is there a reason? 

Concerning the merge, we might keep the PR open to see if there is a strong disagreement on doing so.

**Comment by Mathieu4141** [comment]
> I see that the relationships are missing towards external clusters such ATT&CK. Is there a reason?

I'm unsure what you are referring to?

**Comment by r0ny123** [comment]
Thanks @Mathieu4141 for the PR. But The AKAs for IRANIAN threat groups in MISP is already messed up. So, it needs a lots of fixing. Cleaver already got wrong AKAs. Hence, I am against the merging.

**Comment by Mathieu4141** [comment]
> I mean the `related` field. If we merge, the relationship needs to be transferred and reviewed.

I think all the relationships of `Cutting Kitten` were already all in `Cleaver`

 
> Thanks @Mathieu4141 for the PR. But The AKAs for IRANIAN threat groups in MISP is already messed up. So, it needs a lots of fixing. Cleaver already got wrong AKAs. Hence, I am against the merging.

Agreed, that's what I'm trying to slowly fix :)
Here the only new AKA that's added by the merge is `ITSecTeam`, which seems to be a company related but maybe different than the APT. Is it why you think we shouldn't merge?
If so, what would you think about removing `ITSecTeam` from the aliases of the merged entity, and having another entity for `ITSecTeam` (no AKA) only?

**Comment by adulau** [comment]
Concerning `ITSecTeam`, I would propose to be a stand-alone threat actor. At least for CFR, [it was for the past years](https://www.cfr.org/cyber-operations/itsecteam). The relationship with [Cutting Kitten](https://www.misp-project.org/galaxy.html#_cutting_kitten) is different than a synonym (it's one of the broken synonyms mentioned by @r0ny123)  and would need to create new relationships with `Cutting Kitten`. 

Just a reminder, as the relationships came a bit later, a lot of synonyms were added in the original creation of the threat actor clusters. So moving away for some synonyms into new threat actors with adequate relationships is usually a preferred strategy.

Glad to see discussions on this subject ;-)

**Comment by r0ny123** [comment]
@adulau @Mathieu4141, to be clear, I'm against the merging of CUTTING KITTEN (aka ITsecTeam) into CLEAVER. I was telling that the CLEAVER synonyms were broken. Also, another point is that synonyms should be treated as an overlap not as an 1:1 connection.

**Comment by Mathieu4141** [comment]
@r0ny123 I agree that the synonyms of cleaver are broken.

#### Here are all the aliases of Cleaver + Cutting kitten in MISP

- Cleaver
- Operation Cleaver

The operation labeled by Cylance in 2014
https://attack.mitre.org/groups/G0003/

- G0003

Cleaver id in MITRE
https://attack.mitre.org/groups/G0003/

- 2889
- TG-2889
- Threat Group 2889

> Based on strong circumstantial evidence, CTU researchers assess that TG-2889 is linked to the activity that Cylance described in its December 2014 Operation CLEAVER [report](http://www.cylance.com/assets/Cleaver/Cylance_Operation_Cleaver_Report.pdf). The report documented threat actors using malware disguised as a résumé application that appeared to allow résumés to be submitted to the industrial conglomerate Teledyne. 

https://www.secureworks.com/research/suspected-iran-based-hacker-group-creates-network-of-fake-linkedin-profiles

- Cobalt Gypsy

Is a new denomination of TG2889

> CTU researchers assess that COBALT GYPSY (formerly known as [TG-2889](https://www.secureworks.com/research/suspected-iran-based-hacker-group-creates-network-of-fake-linkedin-profiles)), a threat group associated with Iranian government-directed cyber operations, is likely responsible for these campaigns and the Mia Ash persona.

https://www.secureworks.com/research/the-curious-case-of-mia-ash

- Cutting Kitten

Seems to be considered as an alias for Cleaver

https://www.cfr.org/cyber-operations/operation-cleaver
https://know.netenrich.com/threatintel/threat_actor/Cutting%20Kitten


- Alibaba

> According to a [report](http://www.cylance.com/assets/Cleaver/Cylance_Operation_Cleaver_Report.pdf) published by the security company Cylance, the UK firm wasn’t the unique known victim of the Ali Baba, the APT also had compromised transportation companies in South Korea and Pakistan. Cylance identified the hacking team as [OpCleaver](http://securityaffairs.co/wordpress/30734/intelligence/operation-cleaver-iranian-hackers.html).

https://securityaffairs.co/wordpress/33682/cyber-crime/ali-baba-apt-middle-east.html

- Magic Hound

Different APT, discovered by unit42

https://unit42.paloaltonetworks.com/unit42-magic-hound-campaign-attacks-saudi-targets/
https://securityaffairs.co/wordpress/56348/intelligence/magic-hound-campaign.html

- G0059

It's the Mitre id of Magic Hound

https://attack.mitre.org/groups/G0059/

- APT35
- APT 35

FireEye alias of MagicHound

https://www.secureworks.com/research/threat-profiles/cobalt-illusion
https://www.cfr.org/cyber-operations/apt-35

- Tarh Andishan

Another APT 

- Group 41

Alias of Clever Kitten

- Rocket_Kitten

Another APT, with another entry in the galaxy

- TEMP.Beanie

Alias of Rocket Kitten

- Ghambar

??


#### Proposal

Break `Cleaver` into:
 - Cleaver / Operation Cleaver / G0003 / TG-2889 / Cobalt Gypsy / Cutting Kitten / Alibaba
 - APT 35 / Magic Hound / G0059 (This means adding synonyms and references to the existing APT35 in the galaxy)
 - Tarh Andishan
 - Clever Kitten / Group 41
 - ITsecTeam

@r0ny123 would that make sense for you? If not what would you suggest to fix the threat actor entry?

**Comment by adulau** [comment]
I'm quite in favor of the break into the different threat-actors for the threat-actor galaxy. Thanks @Mathieu4141 for the proposal. As long we update the relationships towards MITRE ones, we are good.  

A side note, for the MITRE ATT&CK ones, we won't change those as it's generated from the MITRE CTI repository and we have no control on this.

For the updates, @r0ny123  should have a second pass to see if it's fine for him too. Then feel free to update this PR or make a one. Thanks a lot.

**Comment by Mathieu4141** [comment]
@r0ny123 How do you feel about this new proposal?

**Comment by r0ny123** [comment]
Check my reviews...

**Comment by Mathieu4141** [comment]
> Check my reviews...

Which one?
I don't see any comment/review from you related to the new proposal I made

**Comment by Mathieu4141** [comment]
@r0ny123 The `Pending` tag on your comments means that you didn't submit your review yet, only you can see it

**Comment by r0ny123** [comment]
@Mathieu4141, it should be visible now.
Thanks for the pointer.

**Comment by Mathieu4141** [comment]
Thanks for your suggestions, I updated the PR accordingly

**Comment by adulau** [comment]
Thanks for the work. I quickly review the PR but it seems the UUID for the same threat actors changed like `7a3f505b-10e9-4177-a96f-d476b55fd3dd`.  For the same actor, they must remain the same. Not sure why it was changed.

**Comment by Mathieu4141** [comment]
Yes sorry about that, it was unintentional

Should be fixed with MISP/misp-galaxy@51aacd6 no?

**Comment by adulau** [comment]
Oh indeed, I missed that commit. Thanks a lot. If everything is fine for you, I'll merge it.

**Comment by Mathieu4141** [comment]
All good on my side :)

**Comment by r0ny123** [comment]
lgtm!

**Comment by adulau** [comment]
Thanks for the contributions and the exchange!

**Pull request merged**
