### PR TITLE
Added references

### PR DESCRIPTION
**Pull request by chrisdoman**
Mostly added references to existing groups
Capitalised DarkHotel, put a space in APT30 default name (the others
had that)

### CODE REVIEW

**Comment by Rafiot** [comment]
Can you please run `jq_all_the_things.sh`, pease? 

https://github.com/MISP/misp-galaxy/blob/master/jq_all_the_things.sh

**Comment by chrisdoman** [comment]
Cheers - have done

**Comment by chrisdoman** [comment]
Hmm travis is still saying there's an issue, I'll take a look

**Comment by adulau** [comment]
Thank you very much. I just added a newline at the end of the file ;-) and now the test passed.

**Comment by chrisdoman** [comment]
Hah that was easy :)

**Pull request merged**
