### PR TITLE
Gutemberg work..

### PR DESCRIPTION
**Pull request by Th4nat0s**
Ok... It need an editing tools and some grabber :).. 

Temporarely,  Here my humble help ...  To me theses informations are definitively important for any qualification.

### CODE REVIEW

**Comment by Th4nat0s** [comment]
Just seen, that type is not an array but a string... seems not too open to qualify a tool/rat...

**Comment by Rafiot** [comment]
Can you JQ all the things, please? -> https://github.com/MISP/misp-galaxy/blob/master/jq_all_the_things.sh :)

**Comment by Th4nat0s** [comment]
I'm on it rafiot, the jq is not the issue, the schema is.. wait.. waiiit :)

**Comment by Rafiot** [comment]
The schema can be changed, I made it super strict so it screams a lot, but if you have a reason to change it, please tell us :)

**Comment by Th4nat0s** [comment]
Yeeeepeee.. i will change the type in array so.. because for some multiples "type" occurs...

PWOBot is to me a "dropper, coinminer, and spyware". 

Does using "type" make sense for you ?

**Comment by adulau** [comment]
Somehow. If the type can be taken from an existing list (like the ms-caro in the taxonomy) that would be great but not a requirement.

**Comment by Th4nat0s** [comment]
Well, It could be used as names, no pbm.. 

But i should change the format anyway.. 

In metadata : 
"type": { "type": "string" }   ----> to  
"type": { "type": "array", "uniqueItems": true, "items": { "type": "string" }

Make sense ? go for that...   But where is the ms-caro source ?? https://github.com/MISP/misp-taxonomies

**Comment by adulau** [comment]
The nice thing with the misp-galaxy is that a key in meta can be a string or an array. This is automatically handled by MISP core.

**Comment by adulau** [comment]
Good point for the miner. maybe we should expand https://github.com/MISP/misp-taxonomies/tree/master/malware_classification ;-)

**Comment by Th4nat0s** [comment]
Ok, I take a look to CARO, Nice but... Miss to me

miner, dropper (like, reco tool, banking
In caro,  RAT = Backdoor... huge assimilation to me :) one got a fancy gui, the other open a rev shell :)

**Comment by adulau** [comment]
Thank you very much for the Gutenberg performance ;-) :medal_military:

**Pull request merged**
