### PR TITLE
Gutemberg II

### PR DESCRIPTION
**Pull request by Th4nat0s**
Bunch of cleanup/Additions...

I will definitively start an fancy editor :)

### CODE REVIEW

**Comment by Rafiot** [comment]
FYI, there is that thing I wanted to play with: https://github.com/jdorn/json-editor

(which is the reason I wrote the schemas :) )

**Comment by Th4nat0s** [comment]
Yep... I need that !...   where is apt-get flaskangularjsonschemawtf !

**Comment by Rafiot** [comment]
well, you said you want to start a fancy editor... :P

**Comment by adulau** [comment]
The "target" idea with discussed with @Rafiot  is to have a public cluster editor where everyone can propose changes and a small core team of MISP copyists can review it and merge it officially. 

As your current changes are very interesting, I'll directly update the galaxy in MISP core HEAD.

Thank you again.

**Comment by Th4nat0s** [comment]
Do you wan't this editor, "alone"  ( python/flask ) or integrated in the misp ?

**Comment by Rafiot** [comment]
yes, standalone (python/flask) would be the best :)

**Pull request merged**
