### PR TITLE
Update threat-actor.json

### PR DESCRIPTION
**Pull request by r0ny123**

### CODE REVIEW

**Comment by adulau** [comment]
Thanks for the update. But maybe a synonym would be more appropriate?

**Comment by r0ny123** [comment]
I've thought it first, but don't want to create confusions as we already have had with Winnti.

**Comment by adulau** [comment]
In your PR, LookBack is removed. I would add it as synonym. We can have some synonyms across threat actors especially if there are doubt from the analysts. Thanks a lot

**Comment by r0ny123** [comment]
Yeah, I removed the Lookback cause proofpoint never called the TA as Lookback they referenced it as the group behind the malware initially, and now they track the malware under TA410. And I fear that at somepoint one may start calling "lookback TA" here and there. And Lookback is already there in Malpedia. So, I don't think there is any doubt from analysts or otherwise to confirm we can reach to some proofpoint guys about this and have their opinion.

**Comment by adulau** [comment]
Thanks for the feedback, it makes sense. Maybe we should add at some point some references to our discussion in the PR directly in the galaxy ;-)

**Comment by r0ny123** [comment]
Yes, this is exactly what we need, more and more open discussions. Thank you!

**Pull request merged**
