### PR TITLE
create new galaxy - surveillance-vendor

### PR DESCRIPTION
**Pull request by Delta-Sierra**
+ add Private Internet Access as Tool

### CODE REVIEW

**Comment by Rafiot** [comment]
This one is also a good addition: https://www.flexispy.com/

And maybe all the other creeps listed there: https://www.bestphonespy.com/category/reviews/

**Comment by Delta-Sierra** [comment]
Thanks! I'll add them asap!

**Comment by adulau** [comment]
`official-refs` must be in `meta`. Could you update it?

**Comment by adulau** [comment]
As seen in the Travis:

~~~~
{'description': 'NSO Group Technologies is an Israeli technology firm known for its Pegasus spyware enabling the remote surveillance of smartphones. It was founded in 2010 by Niv Carmi, Omri Lavie, and Shalev Hulio. It reportedly employed almost 500 people as of 2017, and is based in Herzliya, near Tel Aviv.', 'meta': {'refs': ['https://en.wikipedia.org/wiki/NSO_Group']}, 'official-refs': ['https://www.nsogroup.com/'], 'uuid': '49d8e89f-401d-4d3d-9155-5758a346a4a1', 'value': 'NSO group'}: Additional properties are not allowed ('official-refs' was unexpected)
~~~~

Just put `official-refs` in meta like you explain the RFC ;-)

**Comment by Delta-Sierra** [comment]
AH! 
Indeed didn't see it was out the dictionnary! Gonna fix it

Still I may have an issue we had before when I tried to update the schema then use jq_all_the things, as it deleted entirely the schema file. 
We had a similar issue where it wipe an entire galaxy when there was an error in it, but I'm still not sure how to fix it.

**Pull request merged**
