### PR TITLE
Synced country codes with suspected state sponsor

### PR DESCRIPTION
**Pull request by botherder**
Several actors have a correct suspected state sponsor country from cfr, while missing a country code. For consistency I update those with an appropriate country value.

### CODE REVIEW

**Comment by adulau** [comment]
Good point! Thank you very much for the contribution.

**Comment by 3c7** [comment]
@botherder: Shouldn't DarkHotel be "KR" instead of "KP"?

**Comment by botherder** [comment]
@3c7 Yes, you are right.

**Comment by 3c7** [comment]
K, thx

**Pull request merged**
