### PR TITLE
galaxy related to sigma rules

### PR DESCRIPTION
**Pull request by jstnk9**
I've created a galaxy related to sigma rules. Imported on my MISP for testing purposes and it works. I wonder if it can be a good new MISP galaxy for the community :)

I have in mind add in the future relations with MITRE Techniques galaxy and tools 

image

image

image

image

image

image

### CODE REVIEW

**Comment by jstnk9** [comment]
Also I've in mind add a script to keep it update with new sigma rules in my public repo

**Comment by adulau** [comment]
Thank you very much. It's really nice. Could you run `jq_all_the_things.sh` and `validate_all.sh` and update this PR?

**Comment by adulau** [comment]
Ok, I solved the issues but there is a major one which might need some more work.

There are a lot of duplicate values (which makes sense from the Sigma rule set) but in MISP this is used to generate the tag name to pivot to the cluster galaxy. We would need to add the filename of the yara rule next to the `value` to ensure uniqueness in the name. Would it possible for you to share the script you used for the generation? I can have a look and make it work.

**Comment by jstnk9** [comment]
@adulau Let me fix it and I'll share the final script! thanks for let me know

**Comment by adulau** [comment]
Awesome! Thank you!

**Comment by jstnk9** [comment]
Coming here just to let you know that they are going to modify title fields in the sigma rules :)

My script is able to detect duplicates and print it! I'll publish it during the following days

**Comment by jstnk9** [comment]
Hey @adulau, there is no duplicated titles already in the sigma rules. Everything was fixed here: https://github.com/SigmaHQ/sigma/issues/3727

I will create another PR with the final MISP galaxy.

**Pull request merged**
