### PR TITLE
Update threat-actor.json

### PR DESCRIPTION
**Pull request by StefanKelm**
APT37

### CODE REVIEW

**Comment by r0ny123** [comment]
That report doesn't align with APT37 trade craft though.

**Comment by adulau** [comment]
@StefanKelm what do you think of the point from @r0ny123  ?

**Comment by StefanKelm** [comment]
To be honest: I don't know as I'm not an expert on APT37. I was relying on the authors of that report...

**Comment by r0ny123** [comment]
I think It would be best to add it under Lazarus group for now, the report contains ttps, iocs that aligns with other NK threat actor, reported by other vendors earlier.

**Comment by StefanKelm** [comment]
Will do.

**Pull request closed without merging**
