### PR TITLE
Adding CyberCrime actor profiles from Crowdstrike & Secureworks

### PR DESCRIPTION
**Pull request by r0ny123**

### CODE REVIEW

**Comment by adulau** [comment]
Thanks for the draft pull-request. It's indeed a good idea. A small question why is `Carbanak` removed? Looks like the merge removed it.

**Comment by r0ny123** [comment]
> A small question why is Carbanak removed?

First of all, `CARBANAK` is the name of the backdoor and we shall not be tracking actors according to their malware cause it feels horrible from CTI perspective. This has been [discussed](https://twitter.com/invisig0th/status/1394617997923397636) for a while now. Also, the source code has been [leaked](https://twitter.com/BarryV/status/1121029243327131648), so there are multiple actors abusing it.

**Comment by adulau** [comment]
My issue is that is still used actively in many report. I have seen many report from law-enforcement using CARBANAK for the threat-actor. I think they actively used for the threat actor name and not the tool. I don't mind to remove it but we should mention it in the meta and/or relationship clearly.

**Comment by r0ny123** [comment]
> I have seen many report from law-enforcement using CARBANAK for the threat-actor. I think they actively used for the threat actor name and not the tool.

Yeah, I saw that. But it creates a lot of confusion. Malpedia has a entry for CARBANAK, so I don't think it will be an issue. We can always link articles mentioning CARBANAK related activities. I think that change will better convey the MISP galaxy's standard regarding attribution.

**Review by adulau — CHANGES_REQUESTED** [review]
It looks good to me.  Maybe you can fix MUMMY SPIDER and then we are good to go. I'll add a new meta fields such `naming_ambiguity` for the old Carbanak naming practices. Thanks a lot for your work!

**Comment by adulau** [comment]
Thank you very much for the contribution!

**Pull request merged**
