### PR TITLE
Adding of Firearm and Ammo galaxies

### PR DESCRIPTION
**Pull request by o1mate**
# Firearms and Ammo #
### Added two new galaxies ###

1. An ammunition galaxy containing a list of known sold ammunition ordered by brands
2. A firearm galaxy containing two clusters (handguns, shotguns) scrapped from a famous vendor and ordered by model names. _(Format : Model name - SKU)_
 
 Original project located [here](https://github.com/W4zT3r/FireArms_Intelligence)

### CODE REVIEW

**Comment by adulau** [comment]
Cool stuff! I see an issue as the cluster for the firearms is not matching the others. The tests are passing because those are not read. Could you add the corresponding galaxy files? I suppose you need one for handguns and one for shotguns instead of the firearms alone. Thank you!

**Comment by adulau** [comment]
Then you just need to merge the two clusters into a single one and pointing to the same name for the galaxy. Thanks a lot.

**Comment by o1mate** [comment]
Hello again,
We have merged the two clusters as mentioned before. Now there is only one called firearms containing both of the previous clusters.

**Comment by o1mate** [comment]
Hello,
One of the checks failed to validate, but according to the logs it does not seem to be an issue regarding our files.
Is there a possibility to re-run the checks ?

**Comment by adulau** [comment]
Thanks a lot. We did some clean-up due to the duplicate values.  Would you be able to share with us the script/scrapper used to generate the JSON? we would like to keep those updated automatically.

**Comment by o1mate** [comment]
Hello again!
The scripts that were used are available at [the project's github page](https://github.com/W4zT3r/FireArms_Intelligence).
 
 Thanks a lot for adding our project to MISP!

**Pull request merged**
