### PR TITLE
Update threat-actor.json

### PR DESCRIPTION
**Pull request by r0ny123**

### CODE REVIEW

**Comment by cvandeplas** [comment]
Thank you @r0ny123 , just give a heads-up whenever it's ready to be merged.

**Comment by adulau** [comment]
Thanks for the merge of `Cloud Atlas`this one was on the radar for a long time ;-)

Looking a bit a the meta, I was thinking to add two new meta fields: `first-year-active` and `last-year-active` to better keep track of update for specific threat actors. What do you think? @r0ny123 @cvandeplas

**Comment by r0ny123** [comment]
> Looking a bit a the meta, I was thinking to add two new meta fields: `first-year-active` and `last-year-active` to better track of update for specific threat actors. What do you think? @r0ny123 @cvandeplas

@adulau, I think it is nice but we need to depend on public reporting for updating them from time to time. Also, before we add more meta fields, we need to address the current inconsistency of different meta fields added to an actor throughout the galaxy.

**Comment by adulau** [comment]
For the meta fields, we can slowly added the fields. I just saw some `since` reference. The meta fields are quite lax but we can add those two in the RFCs to be sure that more people use it.

**Comment by r0ny123** [comment]
Do you already have any RFCs for better describing an actor in galaxy?

**Comment by adulau** [comment]
There are some very basic stuff in this part of the MISP galaxy RFC about the meta: 

https://github.com/MISP/misp-rfc/blob/main/misp-galaxy-format/raw.md#meta

But it would be a good opportunity to use the threat-actor galaxy as an example in the RFC and we update it with a specific section.

**Comment by r0ny123** [comment]
Thanks, and yes, we should enforce that in misp-galaxy.

**Pull request merged**
