### PR TITLE
Add FTCode Ransomware

### PR DESCRIPTION
**Pull request by rmkml**

### CODE REVIEW

**Comment by adulau** [comment]
Thank you! Can you fix the current conflict? and update the pull-request?

**Comment by rmkml** [comment]
Sorry for noise, ok fixed, thx you.

**Comment by rmkml** [comment]
This is second times, Travis CI failed, I'm try again tomorrow.

**Comment by adulau** [comment]
No worries, I just fixed it. Thank you for the contribution and enjoy your week-end!

**Pull request merged**
