### PR TITLE
[threat-actors] Add Phosphorus in APT35 aliases

### PR DESCRIPTION
**Pull request by Mathieu4141**

### CODE REVIEW

**Comment by adulau** [comment]
Thanks. I would keep `APT 35` as it's a frequent synonym.

**Comment by Mathieu4141** [comment]
> Thanks. I would keep `APT 35` as it's a frequent synonym.

`APT35` is already the name of the entry

**Comment by r0ny123** [comment]
@adulau there's no space between APT and the number. :)

**Comment by adulau** [comment]
it’s just that I found some references with some other misp communities. I’ll merge it and check with them the strategy for some APT<space>value records used.

**Pull request merged**
